In [1]:
import numpy as np

outcomes = [1,2,3,4,5,6]

n_trials = 2
n_simulations = 1_000_000

In [3]:
dice_rolls = np.random.choice(outcomes, (n_simulations, n_trials))
dice_rolls

array([[5, 2],
       [1, 1],
       [4, 6],
       ...,
       [1, 2],
       [2, 3],
       [4, 3]])

In [14]:
result = sum([1 for roll in dice_rolls if roll[0] == roll[1]])
print(result)

result / n_simulations

167008


0.167008

In [ ]:
result

## How likely is it that you roll doubles when rolling two dice?

## If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [15]:
outcomes = ['H', 'T']

n_trials = 8
n_simulations = 1_000_000

flips = np.random.choice(outcomes, (n_simulations, n_trials))
flips

array([['H', 'H', 'H', ..., 'H', 'T', 'H'],
       ['T', 'H', 'H', ..., 'H', 'H', 'T'],
       ['H', 'T', 'T', ..., 'T', 'H', 'T'],
       ...,
       ['H', 'T', 'H', ..., 'T', 'H', 'T'],
       ['T', 'H', 'H', ..., 'H', 'T', 'T'],
       ['T', 'H', 'T', ..., 'H', 'T', 'H']], dtype='<U1')

In [22]:
three_heads = sum([1 for flip in flips if sum([1 for item in flip if item == 'H']) == 3])
three_heads

218293

In [23]:
three_heads / n_simulations

0.218293

In [24]:
more_than_three_heads = sum([1 for flip in flips if sum([1 for item in flip if item == 'H']) > 3])
more_than_three_heads

636730

In [25]:
more_than_three_heads / n_simulations

0.63673

## There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [30]:
outcomes = ['WD', 'WD', 'WD', 'DS']

n_trials = 2
n_simulations = 1_000_000

drive_bys = np.random.choice(outcomes, (n_simulations, n_trials))
drive_bys

array([['WD', 'WD'],
       ['WD', 'WD'],
       ['DS', 'WD'],
       ...,
       ['WD', 'DS'],
       ['WD', 'WD'],
       ['DS', 'WD']], dtype='<U2')

In [31]:
results = sum([1 for sign in drive_bys if sign[0] == 'DS' and sign[1] == 'DS'])
results

62831

In [32]:
results / n_simulations

0.062831

## Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [152]:

n_trials = 5
n_simulations = 100_000


In [127]:
simulated_weeks = np.random.choice(np.random.normal(loc=3, scale=1.5, size=100000), (n_simulations, n_trials))
simulated_weeks

array([[ 3.38114902,  4.03243757,  3.02063676,  2.75023638,  1.62028006],
       [ 2.40125193,  1.91088914,  2.62880992,  3.68060623,  2.65280616],
       [ 0.33441285,  4.41626158, -0.27776815,  1.84296272,  3.09848732],
       ...,
       [ 2.5099518 ,  4.81879572,  2.85623768,  4.0537389 ,  0.92404929],
       [ 4.99638016,  1.06729792,  1.50109961,  2.93622822,  4.0547425 ],
       [ 4.99759641,  2.98831096,  1.50177281,  3.2625529 ,  0.92339995]])

In [140]:
results = sum([1 for week in simulated_weeks if sum(week)>= 16])
results

38065

In [142]:
1- (results / n_simulations)

0.6193500000000001

## Compare Heights
Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [136]:
m_heights = np.random.normal(loc= 178, scale= 8, size=1000000)
m_heights

f_heights = np.random.normal(loc= 170, scale= 6, size=1000000)
f_heights

array([173.61993317, 179.84890585, 168.89306344, ..., 166.21720316,
       172.85677228, 177.74123261])

In [244]:
results = []
for i in range(1,1000000):
    man = np.random.choice(m_heights, (1,1))
    woman = np.random.choice(f_heights, (1,1))
    if woman > man:
        results.append(True)
        
len(results)/1000000

0.211271

In [293]:
m_heights = np.random.normal(loc= 178, scale= 8, size=100000)
m_heights

f_heights = np.random.normal(loc= 170, scale= 6, size=100000)
f_heights

results = []
for i in range(1,100001):
    man = np.random.choice(m_heights, (1,1))
    woman = np.random.choice(f_heights, (1,1))
    if woman > man:
        results.append(True)
        
len(results)/100000

0.21114

## When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

## What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [229]:
outcomes = ['W' for i in range(1,250)]
outcomes.append('F')


n_trials = 50
n_simulations = 1000000

In [172]:
install_sessions = np.random.choice(outcomes, (n_simulations, n_trials))
install_sessions

array([['W', 'W', 'W', ..., 'W', 'W', 'W'],
       ['W', 'W', 'W', ..., 'W', 'W', 'W'],
       ['W', 'W', 'W', ..., 'W', 'W', 'W'],
       ...,
       ['W', 'W', 'W', ..., 'W', 'W', 'W'],
       ['W', 'W', 'W', ..., 'W', 'W', 'W'],
       ['W', 'W', 'W', ..., 'W', 'W', 'W']], dtype='<U1')

In [173]:
failed_sessions = len([1 for session in install_sessions if len([1 for char in session if char == 'F']) > 0])
failed_sessions

181261

In [175]:
1- (failed_sessions / n_simulations)

0.818739

## What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [176]:
n_trials = 150
n_simulations = 1000000


In [ ]:
install_sessions = np.random.choice(outcomes, (n_simulations, n_trials))
install_sessions

In [177]:
failed_sessions = len([1 for session in install_sessions if len([1 for char in session if char == 'F']) > 0])
failed_sessions

452323

In [178]:
failed_sessions / n_simulations

0.452323

## How likely is it that 450 students all download anaconda without an issue?

In [ ]:
n_trials = 450
n_simulations = 1000000


In [182]:
install_sessions = np.random.choice(outcomes, (n_simulations, n_trials))
install_sessions

failed_sessions = len([1 for session in install_sessions if len([1 for char in session if char == 'F']) > 0])
print(failed_sessions)

1- (failed_sessions / n_simulations)

451893


0.548107

## There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [187]:
outcomes = ['T','T','T','T','T','T','T','N','N','N']
outcomes

n_trials = 3
n_simulations = 1_000_000

sim_periods = np.random.choice(outcomes, (n_simulations, n_trials))
sim_periods

array([['N', 'N', 'N'],
       ['N', 'T', 'T'],
       ['T', 'N', 'T'],
       ...,
       ['T', 'T', 'T'],
       ['T', 'N', 'T'],
       ['N', 'N', 'N']], dtype='<U1')

In [189]:
results = len([1 for period in sim_periods if len([1 for char in period if char == 'N']) == 3])
results

26806

In [190]:
results / n_simulations

0.026806

## How likely is it that a food truck will show up sometime this week?

In [191]:
outcomes = ['T','T','T','T','T','T','T','N','N','N']
outcomes

n_trials = 7
n_simulations = 1_000_000

sim_periods = np.random.choice(outcomes, (n_simulations, n_trials))
sim_periods

array([['T', 'N', 'N', ..., 'T', 'T', 'T'],
       ['T', 'T', 'T', ..., 'T', 'T', 'T'],
       ['N', 'T', 'T', ..., 'T', 'T', 'T'],
       ...,
       ['T', 'N', 'T', ..., 'T', 'T', 'T'],
       ['T', 'T', 'T', ..., 'N', 'N', 'T'],
       ['T', 'T', 'T', ..., 'T', 'T', 'T']], dtype='<U1')

In [192]:
results = len([1 for period in sim_periods if len([1 for char in period if char == 'T']) > 0])
results

999760

In [193]:
results / n_simulations

0.99976

## If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [233]:
outcomes = list(range(1, 366))


In [236]:
n_trials =23
n_simulations = 1000000

bday_sessions = np.random.choice(outcomes, (n_simulations, n_trials))
bday_sessions

array([[ 25, 353, 183, ..., 159, 132, 226],
       [154, 146, 244, ..., 218,  99, 345],
       [253, 173, 118, ..., 346, 342, 213],
       ...,
       [134,  44, 349, ..., 183,   4,  74],
       [345, 237,  70, ..., 309, 361, 170],
       [ 38,  88, 112, ...,  59, 126,  27]])

In [237]:
results = len([1 for session in bday_sessions if len(session) != len(set(session))])
results / n_simulations

0.507368